### ISSUE TITLE
Power consumption graph not displaying data

### ISSUE THREAD

**Issue by GodAtum360** [tess1o/go-tapo-exporter#1]
Eveyrthing else displays the correct data apart from the grpah, as shown in the attached screenshot.
![Capture](https://github.com/user-attachments/assets/696688e3-305e-4514-90a2-8bcdc415ba8e)

**Comment by krax0x** [comment]
There is an easy fix, it's just a hardcoded setting for the "fridge" which it was made with.

Steps to fix:

1. Edit dashboard
2. Edit Power Consumption graph
3. On right side panel scroll to the bottom and remove the override.

This is visualize other devices aswell, instead only the "Fridge".

PS. Maybe maintainer can commit the dashboard without the hardcoded device to the grafana dashboard repo.

**Comment by GodAtum360** [comment]
Thank you that fixed it

**Comment by tess1o** [comment]
Thanks for creating the issue and finding the root cause. I've also uploaded the fix to grafana.com (3rd revision)

https://grafana.com/grafana/dashboards/21982-energy-monitoring/
